package com.wode.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-24T16:36:09.683+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://server.wode.com/", name = "MyWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface MyWebService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://server.wode.com/", className = "com.wode.server.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.wode.com/", className = "com.wode.server.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "firstA", targetNamespace = "")
        int firstA,
        @WebParam(name = "firstB", targetNamespace = "")
        int firstB
    );

    @WebMethod
    @RequestWrapper(localName = "minus", targetNamespace = "http://server.wode.com/", className = "com.wode.server.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://server.wode.com/", className = "com.wode.server.MinusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int minus(
        @WebParam(name = "secondA", targetNamespace = "")
        int secondA,
        @WebParam(name = "secondB", targetNamespace = "")
        int secondB
    );
}
